version: '3'

services:
  api:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: gtw
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
